//! Review gate + debrief logic (M5, design §4.2/§4.3).
//!
//! The gate runs after an exercise passes its tests:
//! 1. static layer (deterministic, zero LLM): todo!/unimplemented!
//!    residue, abstract-constraint violations, clippy lints, effective
//!    line count — mirroring the project's "能确定性验证的不烧 LLM" rule;
//! 2. LLM layer: an idiomatic-review JSON call (verdict
//!    clean/suggestions/suspicious + findings with concrete fixes);
//! 3. suspicious → one extra probe test generated by the LLM and run
//!    with the real test harness; still failing → not counted as
//!    mastery.
//!
//! The debrief (explanation check, better-solution challenge,
//! two-dimensional comparison, follow-up decision) lives in
//! `cli/debrief.rs` for the interactive part; the pure decision logic
//! (`decide_follow_up`, comparison data assembly) stays here so it is
//! unit-testable without a terminal.

use std::sync::OnceLock;
use std::time::Duration;

use anyhow::{anyhow, bail, Result};
use serde_json::Value;

use crate::constraints::{self, Constraint};
use crate::llm::LlmReply;
use crate::verifier;

// ---------------------------------------------------------------------------
// Verdict & findings (§4.2 LLM layer shape)
// ---------------------------------------------------------------------------

/// Gate verdict. Ordered: a bigger rank wins when combining layers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Verdict {
    /// Idiomatic, nothing to flag.
    Clean,
    /// Passes, but with concrete improvement points.
    Suggestions,
    /// Probably dodged the point of the exercise (dead todo!,
    /// hard-coded expectations, empty stub) → probe test required.
    Suspicious,
}

impl Verdict {
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "clean" => Some(Verdict::Clean),
            "suggestions" => Some(Verdict::Suggestions),
            "suspicious" => Some(Verdict::Suspicious),
            _ => None,
        }
    }

    /// Human label for the CLI (中文).
    pub fn label_cn(&self) -> &'static str {
        match self {
            Verdict::Clean => "通过 · 写法地道",
            Verdict::Suggestions => "通过 · 有改进空间",
            Verdict::Suspicious => "存疑 · 需要加测验证",
        }
    }

    /// Stable key persisted in the exercise index (`review_verdict`).
    pub fn key(&self) -> &'static str {
        match self {
            Verdict::Clean => "clean",
            Verdict::Suggestions => "suggestions",
            Verdict::Suspicious => "suspicious",
        }
    }
}

/// One review finding. `kind` ∈ idiom|readability|maintenance|design|logic;
/// `severity` ∈ minor|major.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Finding {
    pub kind: String,
    pub severity: String,
    pub message: String,
    pub better_way: Option<String>,
}

/// The LLM review of one passed solution.
#[derive(Debug, Clone)]
pub struct LlmReview {
    pub verdict: Verdict,
    pub summary: String,
    pub findings: Vec<Finding>,
}

/// Parse the review JSON out of a model reply. Returns None on any
/// shape deviation (the caller degrades to the static-only verdict).
pub fn parse_llm_review(text: &str) -> Option<LlmReview> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let verdict = Verdict::parse(v.get("verdict")?.as_str()?)?;
    let summary = v
        .get("summary")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .trim()
        .to_string();
    let findings = v
        .get("findings")
        .and_then(Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(|f| {
                    let message = f.get("message")?.as_str()?.trim().to_string();
                    if message.is_empty() {
                        return None;
                    }
                    Some(Finding {
                        kind: f
                            .get("kind")
                            .and_then(Value::as_str)
                            .unwrap_or("idiom")
                            .to_string(),
                        severity: f
                            .get("severity")
                            .and_then(Value::as_str)
                            .unwrap_or("minor")
                            .to_string(),
                        message,
                        better_way: f
                            .get("better_way")
                            .and_then(Value::as_str)
                            .map(str::trim)
                            .filter(|s| !s.is_empty())
                            .map(str::to_string),
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    Some(LlmReview { verdict, summary, findings })
}

// ---------------------------------------------------------------------------
// Static layer (§4.2 deterministic checks)
// ---------------------------------------------------------------------------

/// One clippy lint (parsed from clippy-driver's rustc-format JSON).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClippyLint {
    /// e.g. "clippy::redundant_clone".
    pub lint: String,
    pub message: String,
    /// 1-based line in the checked file; 0 when unknown.
    pub line: usize,
}

/// Result of the deterministic layer.
#[derive(Debug, Clone, Default)]
pub struct StaticReport {
    /// Lines (1-based) still containing todo!/unimplemented! macros —
    /// a passing exercise with residue means the tests do not cover
    /// the TODO path (classic §4.2 suspicious signal).
    pub todo_residue: Vec<usize>,
    /// Abstract-constraint violations (no-clone etc.).
    pub violations: Vec<constraints::Violation>,
    pub clippy_lints: Vec<ClippyLint>,
    /// False when clippy-driver is not installed — the gate degrades
    /// honestly instead of pretending the check ran.
    pub clippy_available: bool,
    /// Non-empty, non-comment lines (comparison-table metric).
    pub effective_lines: usize,
}

impl StaticReport {
    pub fn has_todo_residue(&self) -> bool {
        !self.todo_residue.is_empty()
    }

    pub fn has_constraint_violations(&self) -> bool {
        !self.violations.is_empty()
    }
}

/// Implementation-only view of a solution file: everything before the
/// test module (`#[cfg(test)]`). The reference solution has no test
/// module, so measuring the learner's FULL file would inflate the line
/// count and drag test-only clippy lints / constraint hits into the
/// comparison (9.6 手测反馈：行数把 tests 算进去了).
pub fn impl_view(code: &str) -> &str {
    match code.find("#[cfg(test)]") {
        Some(i) => &code[..i],
        None => code,
    }
}

/// Review view of a solution file: implementation only, minus the
/// rustlings progress marker. `// I AM NOT DONE` is a convention the
/// learner is NOT asked to remove — it carries zero review signal and
/// used to be scolded as "scaffolding residue" by the LLM (9.6 手测).
pub fn review_view(code: &str) -> String {
    let no_marker =
        code.lines().filter(|l| !l.contains("I AM NOT DONE")).collect::<Vec<_>>().join("\n");
    impl_view(&no_marker).trim_end().to_string()
}

/// Run the deterministic layer over the user's full solution file.
/// `constraint_specs` are the exercise's declared constraint strings
/// (empty = only todo!/clippy/lines are checked). Measurement uses the
/// implementation-only view (see `impl_view`).
pub fn static_checks(code: &str, constraint_specs: &[String]) -> StaticReport {
    let parsed: Vec<Constraint> = constraint_specs.iter().filter_map(|s| Constraint::from_spec(s)).collect();
    let code = impl_view(code);
    let violations = constraints::check(code, &parsed);

    let stripped = constraints::strip_line_comments(code);
    let todo_residue = stripped
        .lines()
        .enumerate()
        .filter(|(_, l)| {
            let t = l.trim_start();
            t.starts_with("todo!") || t.starts_with("unimplemented!")
        })
        .map(|(i, _)| i + 1)
        .collect();
    let effective_lines = stripped.lines().filter(|l| !l.trim().is_empty()).count();

    let (clippy_lints, clippy_available) = match run_clippy(code) {
        Some(lints) => (lints, true),
        None => (Vec::new(), false),
    };

    StaticReport {
        todo_residue,
        violations,
        clippy_lints,
        clippy_available,
        effective_lines,
    }
}

/// Combine the static layer and the (optional) LLM review into the
/// final gate verdict: the worst rank wins. Static-only rules:
/// todo! residue → suspicious (tests don't cover it), constraint
/// violations → suggestions (objective improvement points).
pub fn combine(statics: &StaticReport, llm: Option<&LlmReview>) -> Verdict {
    let mut worst = if statics.has_todo_residue() {
        Verdict::Suspicious
    } else if statics.has_constraint_violations() {
        Verdict::Suggestions
    } else {
        Verdict::Clean
    };
    if let Some(review) = llm
        && review.verdict > worst
    {
        worst = review.verdict;
    }
    worst
}

// ---------------------------------------------------------------------------
// clippy integration
// ---------------------------------------------------------------------------

const CLIPPY_TIMEOUT: Duration = Duration::from_secs(90);

/// Whether `clippy-driver` is installed (checked once per process).
pub fn clippy_available() -> bool {
    static AVAILABLE: OnceLock<bool> = OnceLock::new();
    *AVAILABLE.get_or_init(|| {
        std::process::Command::new("clippy-driver")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    })
}

/// Run clippy-driver over a single source file (same shape as the
/// rustc --test flow: edition 2024, JSON diagnostics, hard timeout).
/// Returns None when clippy is unavailable or the run failed outright
/// — the caller must distinguish "no lints" from "could not check".
pub fn run_clippy(code: &str) -> Option<Vec<ClippyLint>> {
    if !clippy_available() {
        return None;
    }
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let dir = std::env::temp_dir().join(format!("rustlings_clippy_{nanos}"));
    std::fs::create_dir_all(&dir).ok()?;
    let src = dir.join("snippet.rs");
    let out = dir.join("snippet.meta");
    std::fs::write(&src, code).ok()?;

    let mut cmd = std::process::Command::new("clippy-driver");
    // -W clippy::all (NOT -A warnings: that group-allow would silence
    // clippy's lints too). Rustc's own warnings are filtered out below
    // so the report only carries clippy lints.
    cmd.args(["--edition", "2024", "--test", "--error-format=json", "-W", "clippy::all", "--emit=metadata"]);
    cmd.arg(&src).arg("-o").arg(&out);
    cmd.stdout(std::process::Stdio::piped()).stderr(std::process::Stdio::piped());

    let result = verifier::run_with_timeout(cmd, CLIPPY_TIMEOUT);
    let _ = std::fs::remove_dir_all(&dir);
    match result {
        Ok(verifier::RunOutcome::Done(output)) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let lints = verifier::parse_diagnostics(&stderr)
                .into_iter()
                .filter_map(|d| {
                    let lint = d.code?;
                    if !lint.starts_with("clippy::") {
                        return None;
                    }
                    let line = d.spans.first().map(|s| s.line_start).unwrap_or(0);
                    Some(ClippyLint { lint, message: d.message, line })
                })
                .collect();
            Some(lints)
        }
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// LLM review call (§4.2 layer 2)
// ---------------------------------------------------------------------------

/// One-shot JSON caller for the review/debrief LLM steps. The CLI
/// bridges this to `LlmClient` and records usage with the given phase
/// tag ("review" / "debrief" / "probe" — R6 分相计费).
pub trait ReviewCaller {
    fn call(&mut self, phase: &'static str, system: &str, user: &str, max_tokens: u32) -> Result<LlmReply>;
}

/// Inputs the reviewer sees. Everything comes from real artifacts
/// (template/draft + the user's file + index meta) — no fabrication.
/// Owned data so the gate can run inside a worker thread.
#[derive(Debug, Clone)]
pub struct ReviewInput {
    pub title: String,
    pub concepts: Vec<String>,
    /// The instruction part of the exercise (what the user saw).
    pub body: String,
    /// Expected non-idiomatic patterns the exercise is designed to
    /// force away (template `anti_patterns`).
    pub anti_patterns: Vec<String>,
    /// Root-cause / misconception seeds for the debrief quiz (template
    /// `review_hints`), when the source is recoverable.
    pub review_hints: Option<ReviewHintsSeed>,
    /// The language-transfer intuition behind the trap (template
    /// `confusion`), when available.
    pub confusion: Option<String>,
    /// Hidden reference solution, when persisted (M5.1+).
    pub reference: Option<String>,
    /// The user's full solution file (body + tests).
    pub user_code: String,
    /// The exercise's declared constraint specs (static layer).
    pub constraint_specs: Vec<String>,
    /// Attempts before the passing run (0 = first-try pass).
    pub attempts: u32,
}

const REVIEW_MAX_TOKENS: u32 = 1200;

const REVIEW_SYSTEM: &str = "\
你是 Rust 教练的解答评审器。学习者刚通过了一道 rustlings 式填空小题的全部测试，\
你要判断解答是否「通过但有问题」：更地道的标准写法、多余 clone、能用迭代器却手写循环、\
能用 &str 却用了 String、权限过宽、边界处理粗糙等。只基于给出的代码与参考解判断，不要臆测。\
严格只输出一个 JSON 对象（不要多余文字、不要代码围栏）：
{\"verdict\":\"clean|suggestions|suspicious\",\"summary\":\"一句话总评\",\"findings\":[{\"kind\":\"idiom|readability|maintenance|design|logic\",\"severity\":\"minor|major\",\"message\":\"问题描述（中文，具体到行为止）\",\"better_way\":\"具体改法（中文）\"}]}
verdict 判据：clean=惯用且无显著问题；suggestions=能过但有明确改进点；\
suspicious=疑似绕过考点（如死代码里的 todo!、硬编码测试期望值、空壳实现、测试被改弱）。\
findings 可为空数组；给不出具体改法就不要编造。";

fn review_user_prompt(input: &ReviewInput) -> String {
    let mut p = String::new();
    p.push_str(&format!("题目：《{}》\n", input.title));
    if !input.concepts.is_empty() {
        p.push_str(&format!("概念：{}\n", input.concepts.join("、")));
    }
    p.push_str(&format!("做题尝试次数：{}（0 = 一次通过）\n\n", input.attempts));
    p.push_str("【题面】\n");
    p.push_str(input.body.trim());
    p.push_str("\n\n【学习者的解答（已通过全部测试）】\n```rust\n");
    p.push_str(input.user_code.trim());
    p.push_str("\n```\n");
    if let Some(r) = &input.reference {
        p.push_str("\n【参考解】\n```rust\n");
        p.push_str(r.trim());
        p.push_str("\n```\n");
    }
    if !input.anti_patterns.is_empty() {
        p.push_str("\n【本题预期迫使学习者避开的写法】\n");
        for a in &input.anti_patterns {
            p.push_str(&format!("- {a}\n"));
        }
    }
    if let Some(c) = &input.confusion {
        p.push_str(&format!("\n【本题针对的语言迁移直觉】{c}\n"));
    }
    p.push_str("\n请输出评审 JSON。");
    p
}

/// Ask the model for a solution review. Fails (Err) on transport /
/// truncation / unparseable JSON — the caller then falls back to the
/// static-only verdict and says so honestly.
pub fn llm_review(call: &mut dyn ReviewCaller, input: &ReviewInput) -> Result<LlmReview> {
    let reply = call.call("review", REVIEW_SYSTEM, &review_user_prompt(input), REVIEW_MAX_TOKENS)?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("评审输出在 max_tokens 处被截断");
    }
    parse_llm_review(&reply.content).ok_or_else(|| anyhow!("评审 JSON 无法解析"))
}

// ---------------------------------------------------------------------------
// Gate orchestration (static → LLM → probe)
// ---------------------------------------------------------------------------

/// Full outcome of one review-gate run.
#[derive(Debug, Clone)]
pub struct GateOutcome {
    pub statics: StaticReport,
    pub llm: Option<LlmReview>,
    /// Why the LLM layer (or probe) was skipped/failed — surfaced to
    /// the user honestly ("无 Key / 预算拦截 / 解析失败").
    pub llm_error: Option<String>,
    pub probe: Option<ProbeOutcome>,
    pub verdict: Verdict,
}

impl GateOutcome {
    /// suspicious (probe failed or inconclusive) → not counted as
    /// mastery (design §4.2).
    pub fn counted_as_mastery(&self) -> bool {
        self.verdict != Verdict::Suspicious
    }
}

/// Run the whole gate. `call` is None offline → static-only verdict.
/// LLM-layer failures degrade to static-only with `llm_error` set
/// (never invent a verdict). Progress strings are meant for the CLI
/// spinner ("评审：静态检查…").
pub fn run_gate(
    mut call: Option<Box<dyn ReviewCaller + Send>>,
    input: ReviewInput,
    progress: &dyn Fn(&str),
) -> GateOutcome {
    progress("评审：静态检查（todo! 残留 / 约束 / clippy）…");
    let statics = static_checks(&input.user_code, &input.constraint_specs);

    let mut llm = None;
    let mut llm_error: Option<String> = None;
    if let Some(c) = call.as_mut() {
        progress("评审：LLM 逻辑评审…");
        match llm_review(&mut **c, &input) {
            Ok(r) => llm = Some(r),
            Err(e) => llm_error = Some(format!("{e:#}")),
        }
    }

    let mut verdict = combine(&statics, llm.as_ref());
    let mut probe = None;

    if verdict == Verdict::Suspicious
        && let Some(c) = call.as_mut()
    {
        let reason = llm
            .as_ref()
            .map(|r| {
                if r.summary.is_empty() {
                    "LLM 评审判定解答疑似绕过考点".to_string()
                } else {
                    r.summary.clone()
                }
            })
            .unwrap_or_else(|| "静态检查发现 todo! 残留".to_string());
        progress("评审：生成附加验证测试（probe）…");
        match run_probe(&mut **c, &input, &reason) {
            Ok(p) => {
                if p.passed == Some(true) {
                    // Suspicion cleared: downgrade to the best verdict
                    // the remaining signals support.
                    let findings = llm.as_ref().map(|r| r.findings.len()).unwrap_or(0);
                    verdict = if statics.has_constraint_violations() || findings > 0 {
                        Verdict::Suggestions
                    } else {
                        Verdict::Clean
                    };
                }
                probe = Some(p);
            }
            Err(e) => llm_error = Some(format!("probe 跳过：{e:#}")),
        }
    }

    GateOutcome { statics, llm, llm_error, probe, verdict }
}

// ---------------------------------------------------------------------------
// Debrief Step 1: explanation check (§4.3 quiz + free-input judging)
// ---------------------------------------------------------------------------

/// Root-cause / misconception seeds from the template (`review_hints`),
/// passed through so the quiz stays anchored to the authored trap.
#[derive(Debug, Clone, Default)]
pub struct ReviewHintsSeed {
    pub root_cause: Vec<String>,
    pub misconceptions: Vec<String>,
}/// One quiz option. Exactly one carries `correct = true`.
#[derive(Debug, Clone)]
pub struct QuizOption {
    pub text: String,
    pub correct: bool,
    pub explain: String,
}

/// The Step-1 quiz: "之前为什么不过" (with a failure snapshot) or
/// "这题考什么" (first-try pass, design §4.3).
#[derive(Debug, Clone)]
pub struct Quiz {
    pub question: String,
    pub options: Vec<QuizOption>,
}

impl Quiz {
    /// The explanation of the correct option (for a miss correction).
    pub fn correct_explanation(&self) -> Option<&str> {
        self.options.iter().find(|o| o.correct).map(|o| o.explain.as_str())
    }

    /// Number of options (0 when the model returned garbage).
    pub fn is_usable(&self) -> bool {
        self.question.trim().len() >= 4
            && self.options.len() >= 3
            && self.options.iter().filter(|o| o.correct).count() == 1
    }
}

/// Parse the quiz JSON out of a model reply.
pub fn parse_quiz(text: &str) -> Option<Quiz> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let question = v.get("question")?.as_str()?.trim().to_string();
    let options = v
        .get("options")?
        .as_array()?
        .iter()
        .filter_map(|o| {
            Some(QuizOption {
                text: o.get("text")?.as_str()?.trim().to_string(),
                correct: o.get("correct").and_then(Value::as_bool).unwrap_or(false),
                explain: o.get("explain").and_then(Value::as_str).unwrap_or_default().to_string(),
            })
        })
        .filter(|o| !o.text.is_empty())
        .collect();
    Some(Quiz { question, options })
}

const QUIZ_MAX_TOKENS: u32 = 700;

const QUIZ_SYSTEM: &str = "\
你是 Rust 教练的复盘出题器。学习者刚通过一道填空题的全部测试，现在用一道单选题校核他是否\
真正理解了原理（而不是蒙对的）。严格只输出一个 JSON 对象（不要多余文字、不要代码围栏）：
{\"question\":\"问题（中文，一句）\",\"options\":[{\"text\":\"选项内容（中文，短语或一句话）\",\"correct\":false,\"explain\":\"这个选项对/错的原理（中文，1-2 句，讲机制不复述选项）\"}]}
要求：3-4 个选项；恰好 1 个 correct=true；干扰项必须像真实初学者的误解（优先取素材里的\
误解/根因，不要凭空编造）；有失败快照时问「之前为什么没过」，一次通过时问「这题在考什么」。";

fn quiz_user_prompt(input: &ReviewInput, last_fail: Option<&str>) -> String {
    let mut p = String::new();
    p.push_str(&format!("题目：《{}》\n", input.title));
    if !input.concepts.is_empty() {
        p.push_str(&format!("概念：{}\n", input.concepts.join("、")));
    }
    p.push_str(&format!("做题尝试次数：{}（0 = 一次通过）\n", input.attempts));
    match last_fail {
        Some(code) => p.push_str(&format!("失败快照：学习者之前失败时的真实报错码/信息：{code}\n")),
        None => p.push_str("失败快照：无（一次通过，问题应问「这题在考什么」）\n"),
    }
    p.push_str(&format!("\n【题面】\n{}\n", input.body.trim()));
    p.push_str(&format!("\n【学习者的最终解答】\n```rust\n{}\n```\n", input.user_code.trim()));
    if let Some(c) = &input.confusion {
        p.push_str(&format!("\n【本题针对的语言迁移直觉（出干扰项素材）】{c}\n"));
    }
    let seed = input.review_hints.as_ref();
    if let Some(h) = seed {
        if !h.root_cause.is_empty() {
            p.push_str("\n【正确根因素材（correct 选项应基于它）】\n");
            for r in &h.root_cause {
                p.push_str(&format!("- {r}\n"));
            }
        }
        if !h.misconceptions.is_empty() {
            p.push_str("\n【常见误解素材（干扰项应基于它们）】\n");
            for m in &h.misconceptions {
                p.push_str(&format!("- {m}\n"));
            }
        }
    }
    p.push_str("\n请输出复盘题 JSON。");
    p
}

/// Generate the Step-1 quiz.
pub fn llm_quiz(call: &mut dyn ReviewCaller, input: &ReviewInput, last_fail: Option<&str>) -> Result<Quiz> {
    let reply = call.call("debrief", QUIZ_SYSTEM, &quiz_user_prompt(input, last_fail), QUIZ_MAX_TOKENS)?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("复盘题输出被截断");
    }
    parse_quiz(&reply.content).filter(|q| q.is_usable()).ok_or_else(|| anyhow!("复盘题 JSON 不合格"))
}

/// Result of judging a free-text answer (design §4.3: LLM 对照真实
/// 错误码 + 根因关键词判 hit/miss).
#[derive(Debug, Clone)]
pub struct FreeJudgement {
    pub hit: bool,
    pub why: String,
}

const JUDGE_MAX_TOKENS: u32 = 400;

/// Judge a free-text answer against the quiz's correct explanation.
pub fn judge_free_input(
    call: &mut dyn ReviewCaller,
    quiz: &Quiz,
    answer: &str,
) -> Result<FreeJudgement> {
    let correct = quiz
        .options
        .iter()
        .find(|o| o.correct)
        .map(|o| format!("{} —— {}", o.text, o.explain))
        .unwrap_or_default();
    let system = "\
你是 Rust 教练的复盘判定器。学习者用自由文本回答了一道理解校核题。对照正确答案判定他的\
回答是否抓住了核心机制（表述不精确但机制对 = hit；只是复述题目/明显错误 = miss）。\
严格只输出 JSON：{\"hit\":true|false,\"why\":\"判定理由（中文，一句话）\"}";
    let user = format!(
        "【问题】{}\n【正确答案】{correct}\n【学习者的回答】{answer}\n\n请输出判定 JSON。",
        quiz.question
    );
    let reply = call.call("debrief", system, &user, JUDGE_MAX_TOKENS)?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("判定输出被截断");
    }
    let json = crate::llm::extract_json(&reply.content)
        .ok_or_else(|| anyhow!("判定 JSON 缺失"))?;
    let v: Value = serde_json::from_str(json)?;
    Ok(FreeJudgement {
        hit: v.get("hit").and_then(Value::as_bool).ok_or_else(|| anyhow!("判定 JSON 缺 hit"))?,
        why: v.get("why").and_then(Value::as_str).unwrap_or_default().to_string(),
    })
}

// ---------------------------------------------------------------------------
// Debrief Step 3: two-dimensional comparison (machine + LLM, §4.3)
// ---------------------------------------------------------------------------

/// Machine-measured side of the comparison (deterministic, no LLM).
#[derive(Debug, Clone, Default)]
pub struct SideMetrics {
    pub effective_lines: usize,
    pub clippy_count: usize,
    pub compile_ms: u64,
    pub test_ms: u64,
    /// Sanity signal of the measurement itself (asserted in tests; the
    /// comparison table omits it because both sides passed to get here).
    #[allow(dead_code)]
    pub passes: bool,
    /// Declared abstract constraints satisfied (no-clone etc.); true
    /// when the exercise declares none.
    pub constraints_ok: bool,
}

/// Full machine layer: user solution vs reference.
#[derive(Debug, Clone, Default)]
pub struct MachineComparison {
    pub user: SideMetrics,
    pub reference: Option<SideMetrics>,
    /// Clippy kinds of the user solution ("clippy::x" → count).
    pub user_clippy_kinds: Vec<(String, usize)>,
}

/// Measure both sides with the real toolchain (rustc --test + clippy).
/// Reference side is None when no reference is persisted.
pub fn machine_metrics(
    user_code: &str,
    reference: Option<&str>,
    constraint_specs: &[String],
) -> MachineComparison {
    let parsed: Vec<Constraint> =
        constraint_specs.iter().filter_map(|s| Constraint::from_spec(s)).collect();
    let measure = |code: &str, tag: &str| -> (SideMetrics, Vec<ClippyLint>) {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let workdir = std::env::temp_dir().join(format!("rustlings_cmp_{tag}_{nanos}"));
        let _ = std::fs::create_dir_all(&workdir);
        // Compile & test the FULL file (tests must run); measure the
        // implementation-only view so both sides of the comparison use
        // the same metric scope.
        let timed = verifier::run_test_flow_timed(code, &workdir, tag);
        let _ = std::fs::remove_dir_all(&workdir);
        let (compile_ms, test_ms, passes) = match &timed {
            Ok((run, c, t)) => (*c, *t, run.test.as_ref().map(|t| t.ok).unwrap_or(false)),
            Err(_) => (0, 0, false),
        };
        let impl_code = impl_view(code);
        let lints = run_clippy(impl_code).unwrap_or_default();
        let stripped = constraints::strip_line_comments(impl_code);
        let metrics = SideMetrics {
            effective_lines: stripped.lines().filter(|l| !l.trim().is_empty()).count(),
            clippy_count: lints.len(),
            compile_ms,
            test_ms,
            passes,
            constraints_ok: constraints::check(impl_code, &parsed).is_empty(),
        };
        (metrics, lints)
    };

    let (user, user_lints) = measure(user_code, "user");
    let mut kinds: std::collections::BTreeMap<String, usize> = Default::default();
    for l in &user_lints {
        *kinds.entry(l.lint.clone()).or_default() += 1;
    }
    let reference = reference.map(|r| measure(r, "ref").0);
    MachineComparison { user, reference, user_clippy_kinds: kinds.into_iter().collect() }
}

/// One LLM-judged dimension row of the comparison table (§4.3 LLM
/// 评审维度: 惯用性/可读性/可维护性/设计习惯，1–5 分 + 短评/改法).
#[derive(Debug, Clone)]
pub struct CompareRow {
    pub dim: String,
    pub user_score: Option<u8>,
    pub ref_score: Option<u8>,
    pub user_note: String,
    pub ref_note: String,
}

#[derive(Debug, Clone)]
pub struct LlmComparison {
    pub rows: Vec<CompareRow>,
    pub takeaway: String,
}

pub fn parse_comparison(text: &str) -> Option<LlmComparison> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let rows = v
        .get("rows")?
        .as_array()?
        .iter()
        .filter_map(|r| {
            Some(CompareRow {
                dim: r.get("dim")?.as_str()?.trim().to_string(),
                user_score: r.get("user_score").and_then(Value::as_u64).map(|n| n.min(5) as u8),
                ref_score: r.get("ref_score").and_then(Value::as_u64).map(|n| n.min(5) as u8),
                user_note: r.get("user_note").and_then(Value::as_str).unwrap_or_default().to_string(),
                ref_note: r.get("ref_note").and_then(Value::as_str).unwrap_or_default().to_string(),
            })
        })
        .filter(|r| !r.dim.is_empty())
        .collect();
    let takeaway = v
        .get("takeaway")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .trim()
        .to_string();
    Some(LlmComparison { rows, takeaway })
}

const CMP_MAX_TOKENS: u32 = 1200;

const CMP_SYSTEM: &str = "\
你是 Rust 教练的对比评审器。学习者刚通过练习，现在把学习者的解与参考解放在一起评四个维度：\
idiom=惯用性（是否用了语言的标准手法）、readability=可读性（命名与控制流清晰度）、\
maintenance=可维护性与扩展成本（加一种类型要改几处）、design=设计习惯（权限最小化、\
无多余 clone、边界与 panic 风险）。每维给 1-5 分并给「短评 + 具体改法」——\
机器测不出来的判断才值得你给，不要复述已知数据；分差要能被 note 里的理由支撑。\
评分锚点（B4，四档定标，压缩不同模型间的漂移）：\
5=与参考解同水平，无值得指出的改进；4=基本地道，仅 1–2 处小改进；\
3=能用但明显非最优/手工化（如手写循环代替迭代器、多余 clone）；\
2=多处反模式或扩展成本显著更高；1=恰好通过但与题意/惯用法相悖。\
两个解都到 5 时就都给 5，不要为了拉开分差压分。\
严格只输出 JSON（不要多余文字、不要代码围栏）：\
{\"rows\":[{\"dim\":\"idiom|readability|maintenance|design\",\"user_score\":1,\"ref_score\":5,\"user_note\":\"学习者的短评与具体改法（中文）\",\"ref_note\":\"参考解短评（中文）\"}],\"takeaway\":\"一句话点评取舍：什么时候学习者的写法也可以接受\"}
评分只评代码本身；题目约束（如禁止 clone）下的写法不算缺点。";

fn cmp_user_prompt(input: &ReviewInput, machine: &MachineComparison) -> String {
    let mut p = String::new();
    p.push_str(&format!("题目：《{}》\n", input.title));
    if !input.concepts.is_empty() {
        p.push_str(&format!("概念：{}\n", input.concepts.join("、")));
    }
    p.push_str(&format!("\n【题面】\n{}\n", input.body.trim()));
    p.push_str("\n【学习者的解】\n```rust\n");
    p.push_str(input.user_code.trim());
    p.push_str("\n```\n");
    if let Some(r) = &input.reference {
        p.push_str("\n【参考解】\n```rust\n");
        p.push_str(r.trim());
        p.push_str("\n```\n");
    }
    if !input.anti_patterns.is_empty() {
        p.push_str("\n【本题预期迫使学习者避开的写法】\n");
        for a in &input.anti_patterns {
            p.push_str(&format!("- {a}\n"));
        }
    }
    p.push_str("\n【机器实测（仅供参考，评分要自己给理由）】\n");
    p.push_str(&format!(
        "- 学习者解：有效行数 {} ｜ clippy {} 条 ｜ 编译 {}ms ｜ 测试 {}ms\n",
        machine.user.effective_lines, machine.user.clippy_count, machine.user.compile_ms, machine.user.test_ms
    ));
    if let Some(r) = &machine.reference {
        p.push_str(&format!(
            "- 参考解：有效行数 {} ｜ clippy {} 条 ｜ 编译 {}ms ｜ 测试 {}ms\n",
            r.effective_lines, r.clippy_count, r.compile_ms, r.test_ms
        ));
    }
    p.push_str("\n请输出对比 JSON。");
    p
}

/// Ask the model for the four-dimension comparison.
pub fn llm_comparison(
    call: &mut dyn ReviewCaller,
    input: &ReviewInput,
    machine: &MachineComparison,
) -> Result<LlmComparison> {
    let reply = call.call("debrief", CMP_SYSTEM, &cmp_user_prompt(input, machine), CMP_MAX_TOKENS)?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("对比评审输出被截断");
    }
    parse_comparison(&reply.content).ok_or_else(|| anyhow!("对比 JSON 无法解析"))
}

// ---------------------------------------------------------------------------
// Debrief Step 4: follow-up decision (§4.3 decide_follow_up)
// ---------------------------------------------------------------------------

/// Inputs of the follow-up decision (all observed, no LLM).
#[derive(Debug, Clone)]
pub struct FollowUpInput {
    /// Attempts before the passing run (failures this solve).
    pub attempts_before: u32,
    /// Any static hint was revealed during solving.
    pub used_hints: bool,
    /// Explanation check result; None = skipped.
    pub explanation_hit: Option<bool>,
    /// Final gate verdict.
    pub verdict: Verdict,
    /// The user's solution violated declared constraints.
    pub had_violations: bool,
}

/// What to do after the debrief (§4.3):
/// - 一次通过 + 解释命中 + clean → NextConcept
/// - 通过但解释 miss 或用了提示 → Variant（同概念换槽位变式，M4.10 机制）
/// - 通过但约束未满足 / suggestions / 存疑 → Variant + 附加约束
/// - ≥3 次失败 → 降难度 Variant + 引导看旧错
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FollowUp {
    NextConcept,
    Variant { extra_constraint: bool },
    EasierVariant,
}

pub fn decide_follow_up(i: &FollowUpInput) -> FollowUp {
    if i.attempts_before >= 3 {
        return FollowUp::EasierVariant;
    }
    if i.had_violations || i.verdict != Verdict::Clean {
        return FollowUp::Variant { extra_constraint: true };
    }
    if i.explanation_hit == Some(false) || i.used_hints {
        return FollowUp::Variant { extra_constraint: false };
    }
    FollowUp::NextConcept
}

impl FollowUp {
    /// Human decision line (中文) for the debrief footer.
    pub fn label_cn(&self) -> String {
        match self {
            FollowUp::NextConcept => "状态很好：建议进入下一个概念".to_string(),
            FollowUp::Variant { extra_constraint: false } => {
                "建议来一道同概念的变式题（换槽位/换场景）巩固".to_string()
            }
            FollowUp::Variant { extra_constraint: true } => {
                "建议变式 + 附加约束（把地道的写法练成本能）".to_string()
            }
            FollowUp::EasierVariant => {
                "失败次数较多：建议来一道降难度的变式，并回看之前的报错".to_string()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Probe test (§4.2 suspicious path)
// ---------------------------------------------------------------------------

/// Result of the extra verification test for a suspicious solution.
#[derive(Debug, Clone)]
pub struct ProbeOutcome {
    /// The test module the LLM produced (already appended & compiled).
    pub test_code: String,
    /// None = the probe itself failed to compile/run (treated as
    /// inconclusive, NOT as a pass).
    pub passed: Option<bool>,
    /// Human-readable failure output when it did not pass.
    pub failure: Option<String>,
}

const PROBE_MAX_TOKENS: u32 = 800;

const PROBE_SYSTEM: &str = "\
你为 Rust 练习生成一道附加验证测试（probe test）。学习者的解答通过了原测试，但被评审判定为\
「疑似绕过考点」。你的任务：写一个**最小**的附加测试，直接检验本题的核心行为是否真正实现\
（而不是重新检验原测试已经覆盖的东西）。严格只输出一个 JSON 对象：
{\"reasoning\":\"一句话：这个测试为什么能暴露绕过\",\"test\":\"完整的 #[cfg(test)] mod probe_tests { ... } 代码（Rust 源码，含 use super::*;）\"}
约束：测试必须编译通过；不得修改/删除已有代码；不得使用 unsafe / std::process / std::fs；\
不要在测试里写 todo!。test 字段的代码将被原样追加到学习者文件末尾编译运行。";

fn probe_user_prompt(input: &ReviewInput, suspicious_reason: &str) -> String {
    format!(
        "题目：《{}》\n概念：{}\n\n【题面】\n{}\n\n【学习者的解答】\n```rust\n{}\n```\n\n\
         【评审判为存疑的理由】{}\n\n请输出 probe test JSON。",
        input.title,
        input.concepts.join("、"),
        input.body.trim(),
        input.user_code.trim(),
        suspicious_reason,
    )
}

pub fn parse_probe(text: &str) -> Option<(String, String)> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let test = v.get("test")?.as_str()?.trim().to_string();
    if test.is_empty() {
        return None;
    }
    let reasoning = v
        .get("reasoning")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    Some((reasoning, test))
}

/// Generate and run the probe test against the user's file. Returns
/// `Ok(None)`-shaped results via `ProbeOutcome.passed = None` when the
/// probe itself could not be produced or compiled (inconclusive).
pub fn run_probe(
    call: &mut dyn ReviewCaller,
    input: &ReviewInput,
    suspicious_reason: &str,
) -> Result<ProbeOutcome> {
    let reply = call.call(
        "probe",
        PROBE_SYSTEM,
        &probe_user_prompt(input, suspicious_reason),
        PROBE_MAX_TOKENS,
    )?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("probe 输出被截断");
    }
    let (_reasoning, test_code) =
        parse_probe(&reply.content).ok_or_else(|| anyhow!("probe JSON 无法解析"))?;

    // Compile + run exactly like a practice attempt: user file + probe.
    let mut source = input.user_code.trim_end().to_string();
    source.push_str("\n\n");
    source.push_str(&test_code);

    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let workdir = std::env::temp_dir().join(format!("rustlings_probe_{nanos}"));
    std::fs::create_dir_all(&workdir)?;
    let run = verifier::run_test_flow(&source, &workdir, "probe");
    let _ = std::fs::remove_dir_all(&workdir);
    let run = run?;
    if !run.compiled {
        return Ok(ProbeOutcome {
            test_code,
            passed: None,
            failure: Some(probe_failure_text(&run.diagnostics)),
        });
    }
    match run.test {
        Some(t) if t.ok => Ok(ProbeOutcome { test_code, passed: Some(true), failure: None }),
        Some(t) => {
            let failure = t
                .failures
                .first()
                .map(|f| {
                    let mut s = f.output.clone();
                    if s.chars().count() > 600 {
                        s = s.chars().take(600).collect();
                    }
                    s
                })
                .unwrap_or_else(|| "probe 测试未通过".to_string());
            Ok(ProbeOutcome { test_code, passed: Some(false), failure: Some(failure) })
        }
        None => Ok(ProbeOutcome { test_code, passed: None, failure: None }),
    }
}

fn probe_failure_text(diags: &[verifier::Diagnostic]) -> String {
    let mut s = String::new();
    for d in diags.iter().filter(|d| d.is_error()).take(3) {
        if !s.is_empty() {
            s.push('\n');
        }
        s.push_str(d.rendered.as_deref().unwrap_or(&d.message));
        if s.chars().count() > 600 {
            s = s.chars().take(600).collect();
            break;
        }
    }
    if s.is_empty() {
        s = "probe 测试编译失败".to_string();
    }
    s
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verdict_parse_and_order() {
        assert_eq!(Verdict::parse("clean"), Some(Verdict::Clean));
        assert_eq!(Verdict::parse(" Suspicious "), Some(Verdict::Suspicious));
        assert_eq!(Verdict::parse("nope"), None);
        assert!(Verdict::Suspicious > Verdict::Suggestions);
        assert!(Verdict::Suggestions > Verdict::Clean);
    }

    #[test]
    fn parse_llm_review_full_and_minimal() {
        let full = r#"前面废话
{"verdict":"suggestions","summary":"能用迭代器","findings":[{"kind":"idiom","severity":"minor","message":"手写循环","better_way":"用 map"},{"kind":"idiom","severity":"minor","message":""}]}
后面废话"#;
        let r = parse_llm_review(full).unwrap();
        assert_eq!(r.verdict, Verdict::Suggestions);
        assert_eq!(r.summary, "能用迭代器");
        assert_eq!(r.findings.len(), 1, "empty message filtered");
        assert_eq!(r.findings[0].better_way.as_deref(), Some("用 map"));

        let minimal = r#"{"verdict":"clean","summary":"ok","findings":[]}"#;
        let r = parse_llm_review(minimal).unwrap();
        assert_eq!(r.verdict, Verdict::Clean);
        assert!(r.findings.is_empty());

        assert!(parse_llm_review("not json").is_none());
        assert!(parse_llm_review(r#"{"verdict":"wrong","summary":""}"#).is_none());
    }

    #[test]
    fn combine_takes_the_worst_layer() {
        let mut st = StaticReport::default();
        assert_eq!(combine(&st, None), Verdict::Clean);

        // todo residue → suspicious even when the LLM says clean.
        st.todo_residue = vec![3];
        assert_eq!(combine(&st, Some(&LlmReview {
            verdict: Verdict::Clean,
            summary: String::new(),
            findings: vec![],
        })), Verdict::Suspicious);

        // Constraint violations beat clean.
        st.todo_residue.clear();
        st.violations.push(constraints::Violation {
            constraint: "no-clone".into(),
            line: 2,
            snippet: ".clone()".into(),
            message: "违反约束".into(),
        });
        assert_eq!(combine(&st, None), Verdict::Suggestions);

        // LLM suspicious wins over static suggestions.
        assert_eq!(combine(&st, Some(&LlmReview {
            verdict: Verdict::Suspicious,
            summary: String::new(),
            findings: vec![],
        })), Verdict::Suspicious);
    }

    #[test]
    fn static_checks_finds_residue_violations_and_lines() {
        let code = "// todo! in comment does not count\nfn f() -> u32 {\n    let s = \"x\".to_owned();\n    todo!()\n}\n";
        let report = static_checks(code, &["no-clone".to_string()]);
        assert_eq!(report.todo_residue, vec![4]);
        assert_eq!(report.violations.len(), 1);
        assert_eq!(report.violations[0].constraint, "no-clone");
        assert_eq!(report.effective_lines, 4, "comment line excluded");
        assert!(report.has_todo_residue() && report.has_constraint_violations());
    }

    #[test]
    fn effective_lines_excludes_test_module_and_marker() {
        // 9.6 手测反馈：the learner's file carries the template's test
        // module and the rustlings marker; neither may inflate the
        // metrics that are compared against the (bare) reference.
        let code = "\
// 场景说明注释。
fn add(a: i32, b: i32) -> i32 {
    a + b
}
// I AM NOT DONE
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn t() {
        assert_eq!(add(1, 2), 3);
    }
}
";
        let report = static_checks(code, &[]);
        assert_eq!(report.effective_lines, 3, "impl only: signature + body + closing brace");
        let view = review_view(code);
        assert!(!view.contains("I AM NOT DONE"), "marker stripped: {view}");
        assert!(!view.contains("mod tests"), "test module stripped: {view}");
        assert!(view.contains("fn add"), "implementation kept: {view}");
    }

    #[test]
    fn clippy_either_runs_or_honestly_reports_unavailable() {
        // Environment-dependent: only assert consistency between the
        // availability probe and the run result.
        let avail = clippy_available();
        let lints = run_clippy("fn f() { let v: Vec<u32> = Vec::new(); v; }");
        if avail {
            assert!(lints.is_some(), "clippy installed but run failed");
        } else {
            assert!(lints.is_none());
        }
    }

    /// A cloned-heavy snippet should yield at least one clippy lint
    /// when clippy exists (redundant clone / unused variable family).
    #[test]
    fn clippy_flags_redundant_clone_when_available() {
        if !clippy_available() {
            return;
        }
        let code = "fn f(s: &str) -> String {\n    let a = s.to_string();\n    let b = a.clone();\n    b\n}\n";
        let lints = run_clippy(code).unwrap();
        assert!(!lints.is_empty(), "expected clippy lints, got none");
        assert!(lints.iter().all(|l| l.lint.contains("clippy::")), "{lints:?}");
    }

    #[test]
    fn parse_probe_extracts_test_field() {
        let reply = r##"{"reasoning":"检查空输入","test":"#[cfg(test)]\nmod probe_tests { use super::*; #[test] fn t() { assert!(true); } }"}"##;
        let (reasoning, test) = parse_probe(reply).unwrap();
        assert!(reasoning.contains("空输入"));
        assert!(test.contains("mod probe_tests"));
        assert!(parse_probe("{\"reasoning\":\"x\"}").is_none());
    }

    #[test]
    fn parse_quiz_validates_single_correct_option() {
        let good = r#"{"question":"这题在考什么？","options":[
            {"text":"A","correct":true,"explain":"因为所有权移动"},
            {"text":"B","correct":false,"explain":"误解一"},
            {"text":"C","correct":false,"explain":"误解二"}]}"#;
        let q = parse_quiz(good).unwrap();
        assert!(q.is_usable());
        assert_eq!(q.correct_explanation(), Some("因为所有权移动"));

        // Two corrects → unusable.
        let bad = r#"{"question":"q?","options":[
            {"text":"A","correct":true,"explain":"x"},
            {"text":"B","correct":true,"explain":"y"},
            {"text":"C","correct":false,"explain":"z"}]}"#;
        let q = parse_quiz(bad).unwrap();
        assert!(!q.is_usable());
        assert!(parse_quiz("nope").is_none());
    }

    #[test]
    fn quiz_prompt_uses_failure_snapshot_and_seeds() {
        let input = ReviewInput {
            title: "题".into(),
            concepts: vec![],
            body: "题面".into(),
            anti_patterns: vec![],
            review_hints: Some(ReviewHintsSeed {
                root_cause: vec!["值被移动后原变量失效".into()],
                misconceptions: vec!["以为 Copy 语义".into()],
            }),
            confusion: Some("C 直觉".into()),
            reference: None,
            user_code: "fn f() {}".into(),
            constraint_specs: vec![],
            attempts: 1,
        };
        let p = quiz_user_prompt(&input, Some("E0382"));
        assert!(p.contains("E0382") && p.contains("正确根因素材") && p.contains("常见误解素材"));
        let p2 = quiz_user_prompt(&input, None);
        assert!(p2.contains("一次通过"));
    }

    #[test]
    fn parse_comparison_rows_and_takeaway() {
        let text = r#"{"rows":[
            {"dim":"idiom","user_score":3,"ref_score":5,"user_note":"手写循环","ref_note":"迭代器链"},
            {"dim":"readability","user_score":4,"ref_score":4,"user_note":"","ref_note":"清晰"}
        ],"takeaway":"学习者写法在小规模下也可接受"}"#;
        let c = parse_comparison(text).unwrap();
        assert_eq!(c.rows.len(), 2);
        assert_eq!(c.rows[0].user_score, Some(3));
        assert_eq!(c.takeaway, "学习者写法在小规模下也可接受");
        // Score above 5 clamped.
        let c2 = parse_comparison(r#"{"rows":[{"dim":"idiom","user_score":9,"ref_score":5,"user_note":"n","ref_note":"r"}],"takeaway":""}"#).unwrap();
        assert_eq!(c2.rows[0].user_score, Some(5));
        assert!(parse_comparison("garbage").is_none());
    }

    #[test]
    fn machine_metrics_measures_both_sides() {
        let user = "fn f(v: &[u32]) -> u32 {\n    let mut s = 0u32;\n    for x in v {\n        s += x;\n    }\n    s\n}\n\n#[cfg(test)]\nmod t {\n    #[test]\n    fn it() {\n        assert_eq!(super::f(&[1, 2, 3]), 6);\n    }\n}\n";
        let reference = "fn f(v: &[u32]) -> u32 {\n    v.iter().sum()\n}\n\n#[cfg(test)]\nmod t {\n    #[test]\n    fn it() {\n        assert_eq!(super::f(&[1, 2, 3]), 6);\n    }\n}\n";
        let m = machine_metrics(user, Some(reference), &["iterator-only".to_string()]);
        assert!(m.user.passes, "user side must pass its tests");
        assert!(m.reference.as_ref().map(|r| r.passes).unwrap_or(false));
        assert!(m.user.effective_lines > m.reference.as_ref().unwrap().effective_lines);
        assert!(!m.user.constraints_ok, "for-loop violates iterator-only");
        assert!(m.reference.as_ref().unwrap().constraints_ok);
        assert!(m.user.compile_ms > 0);
    }

    #[test]
    fn decide_follow_up_covers_all_branches() {
        let base = FollowUpInput {
            attempts_before: 0,
            used_hints: false,
            explanation_hit: Some(true),
            verdict: Verdict::Clean,
            had_violations: false,
        };
        assert_eq!(decide_follow_up(&base), FollowUp::NextConcept);

        // Miss on the explanation → plain variant.
        let miss = FollowUpInput { explanation_hit: Some(false), ..base.clone() };
        assert_eq!(decide_follow_up(&miss), FollowUp::Variant { extra_constraint: false });

        // Hints used → plain variant.
        let hints = FollowUpInput { used_hints: true, ..base.clone() };
        assert_eq!(decide_follow_up(&hints), FollowUp::Variant { extra_constraint: false });

        // Suggestions / violations / suspicious → variant + constraint.
        let sugg = FollowUpInput { verdict: Verdict::Suggestions, ..base.clone() };
        assert_eq!(decide_follow_up(&sugg), FollowUp::Variant { extra_constraint: true });
        let viol = FollowUpInput { had_violations: true, ..base.clone() };
        assert_eq!(decide_follow_up(&viol), FollowUp::Variant { extra_constraint: true });
        let sus = FollowUpInput { verdict: Verdict::Suspicious, ..base.clone() };
        assert_eq!(decide_follow_up(&sus), FollowUp::Variant { extra_constraint: true });

        // ≥3 failures wins over everything.
        let hard = FollowUpInput { attempts_before: 3, ..sugg };
        assert_eq!(decide_follow_up(&hard), FollowUp::EasierVariant);

        // Skipped explanation (None) does not count as a miss.
        let skipped = FollowUpInput { explanation_hit: None, ..base };
        assert_eq!(decide_follow_up(&skipped), FollowUp::NextConcept);
    }

    #[test]
    fn review_user_prompt_contains_all_sections() {
        let input = ReviewInput {
            title: "题".into(),
            concepts: vec!["ownership.move".to_string()],
            body: "// TODO".into(),
            anti_patterns: vec!["clone 逃逸".to_string()],
            review_hints: None,
            confusion: Some("来自 C 的值语义直觉".into()),
            reference: Some("fn f() {}".into()),
            user_code: "fn f() { todo!() }".into(),
            constraint_specs: vec![],
            attempts: 2,
        };
        let p = review_user_prompt(&input);
        assert!(p.contains("题面") && p.contains("参考解") && p.contains("clone 逃逸"));
        assert!(p.contains("语言迁移直觉") && p.contains("2"));
    }
}
