//! Review gate + debrief logic (M5, design §4.2/§4.3).
//!
//! The gate runs after an exercise passes its tests:
//! 1. static layer (deterministic, zero LLM): todo!/unimplemented!
//!    residue, abstract-constraint violations, clippy lints, effective
//!    line count — mirroring the project's "能确定性验证的不烧 LLM" rule;
//! 2. LLM layer: an idiomatic-review JSON call (verdict
//!    clean/suggestions/suspicious + findings with concrete fixes);
//! 3. suspicious → one extra probe test generated by the LLM and run
//!    with the real test harness; still failing → not counted as
//!    mastery.
//!
//! The debrief (explanation check, better-solution challenge,
//! two-dimensional comparison, follow-up decision) lives in
//! `cli/debrief.rs` for the interactive part; the pure decision logic
//! (`decide_follow_up`, comparison data assembly) stays here so it is
//! unit-testable without a terminal.

use std::sync::OnceLock;
use std::time::Duration;

use anyhow::{anyhow, bail, Result};
use serde_json::Value;

use crate::constraints::{self, Constraint};
use crate::llm::LlmReply;
use crate::verifier;

// ---------------------------------------------------------------------------
// Verdict & findings (§4.2 LLM layer shape)
// ---------------------------------------------------------------------------

/// Gate verdict. Ordered: a bigger rank wins when combining layers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Verdict {
    /// Idiomatic, nothing to flag.
    Clean,
    /// Passes, but with concrete improvement points.
    Suggestions,
    /// Probably dodged the point of the exercise (dead todo!,
    /// hard-coded expectations, empty stub) → probe test required.
    Suspicious,
}

impl Verdict {
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "clean" => Some(Verdict::Clean),
            "suggestions" => Some(Verdict::Suggestions),
            "suspicious" => Some(Verdict::Suspicious),
            _ => None,
        }
    }

    /// Human label for the CLI (中文).
    pub fn label_cn(&self) -> &'static str {
        match self {
            Verdict::Clean => "通过 · 写法地道",
            Verdict::Suggestions => "通过 · 有改进空间",
            Verdict::Suspicious => "存疑 · 需要加测验证",
        }
    }
}

/// One review finding. `kind` ∈ idiom|readability|maintenance|design|logic;
/// `severity` ∈ minor|major.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Finding {
    pub kind: String,
    pub severity: String,
    pub message: String,
    pub better_way: Option<String>,
}

/// The LLM review of one passed solution.
#[derive(Debug, Clone)]
pub struct LlmReview {
    pub verdict: Verdict,
    pub summary: String,
    pub findings: Vec<Finding>,
}

/// Parse the review JSON out of a model reply. Returns None on any
/// shape deviation (the caller degrades to the static-only verdict).
pub fn parse_llm_review(text: &str) -> Option<LlmReview> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let verdict = Verdict::parse(v.get("verdict")?.as_str()?)?;
    let summary = v
        .get("summary")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .trim()
        .to_string();
    let findings = v
        .get("findings")
        .and_then(Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(|f| {
                    let message = f.get("message")?.as_str()?.trim().to_string();
                    if message.is_empty() {
                        return None;
                    }
                    Some(Finding {
                        kind: f
                            .get("kind")
                            .and_then(Value::as_str)
                            .unwrap_or("idiom")
                            .to_string(),
                        severity: f
                            .get("severity")
                            .and_then(Value::as_str)
                            .unwrap_or("minor")
                            .to_string(),
                        message,
                        better_way: f
                            .get("better_way")
                            .and_then(Value::as_str)
                            .map(str::trim)
                            .filter(|s| !s.is_empty())
                            .map(str::to_string),
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    Some(LlmReview { verdict, summary, findings })
}

// ---------------------------------------------------------------------------
// Static layer (§4.2 deterministic checks)
// ---------------------------------------------------------------------------

/// One clippy lint (parsed from clippy-driver's rustc-format JSON).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClippyLint {
    /// e.g. "clippy::redundant_clone".
    pub lint: String,
    pub message: String,
    /// 1-based line in the checked file; 0 when unknown.
    pub line: usize,
}

/// Result of the deterministic layer.
#[derive(Debug, Clone, Default)]
pub struct StaticReport {
    /// Lines (1-based) still containing todo!/unimplemented! macros —
    /// a passing exercise with residue means the tests do not cover
    /// the TODO path (classic §4.2 suspicious signal).
    pub todo_residue: Vec<usize>,
    /// Abstract-constraint violations (no-clone etc.).
    pub violations: Vec<constraints::Violation>,
    pub clippy_lints: Vec<ClippyLint>,
    /// False when clippy-driver is not installed — the gate degrades
    /// honestly instead of pretending the check ran.
    pub clippy_available: bool,
    /// Non-empty, non-comment lines (comparison-table metric).
    pub effective_lines: usize,
}

impl StaticReport {
    pub fn has_todo_residue(&self) -> bool {
        !self.todo_residue.is_empty()
    }

    pub fn has_constraint_violations(&self) -> bool {
        !self.violations.is_empty()
    }
}

/// Run the deterministic layer over the user's full solution file.
/// `constraint_specs` are the exercise's declared constraint strings
/// (empty = only todo!/clippy/lines are checked).
pub fn static_checks(code: &str, constraint_specs: &[String]) -> StaticReport {
    let parsed: Vec<Constraint> = constraint_specs.iter().filter_map(|s| Constraint::from_spec(s)).collect();
    let violations = constraints::check(code, &parsed);

    let stripped = constraints::strip_line_comments(code);
    let todo_residue = stripped
        .lines()
        .enumerate()
        .filter(|(_, l)| {
            let t = l.trim_start();
            t.starts_with("todo!") || t.starts_with("unimplemented!")
        })
        .map(|(i, _)| i + 1)
        .collect();
    let effective_lines = stripped.lines().filter(|l| !l.trim().is_empty()).count();

    let (clippy_lints, clippy_available) = match run_clippy(code) {
        Some(lints) => (lints, true),
        None => (Vec::new(), false),
    };

    StaticReport {
        todo_residue,
        violations,
        clippy_lints,
        clippy_available,
        effective_lines,
    }
}

/// Combine the static layer and the (optional) LLM review into the
/// final gate verdict: the worst rank wins. Static-only rules:
/// todo! residue → suspicious (tests don't cover it), constraint
/// violations → suggestions (objective improvement points).
pub fn combine(statics: &StaticReport, llm: Option<&LlmReview>) -> Verdict {
    let mut worst = if statics.has_todo_residue() {
        Verdict::Suspicious
    } else if statics.has_constraint_violations() {
        Verdict::Suggestions
    } else {
        Verdict::Clean
    };
    if let Some(review) = llm
        && review.verdict > worst
    {
        worst = review.verdict;
    }
    worst
}

// ---------------------------------------------------------------------------
// clippy integration
// ---------------------------------------------------------------------------

const CLIPPY_TIMEOUT: Duration = Duration::from_secs(90);

/// Whether `clippy-driver` is installed (checked once per process).
pub fn clippy_available() -> bool {
    static AVAILABLE: OnceLock<bool> = OnceLock::new();
    *AVAILABLE.get_or_init(|| {
        std::process::Command::new("clippy-driver")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    })
}

/// Run clippy-driver over a single source file (same shape as the
/// rustc --test flow: edition 2024, JSON diagnostics, hard timeout).
/// Returns None when clippy is unavailable or the run failed outright
/// — the caller must distinguish "no lints" from "could not check".
pub fn run_clippy(code: &str) -> Option<Vec<ClippyLint>> {
    if !clippy_available() {
        return None;
    }
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let dir = std::env::temp_dir().join(format!("rustlings_clippy_{nanos}"));
    std::fs::create_dir_all(&dir).ok()?;
    let src = dir.join("snippet.rs");
    let out = dir.join("snippet.meta");
    std::fs::write(&src, code).ok()?;

    let mut cmd = std::process::Command::new("clippy-driver");
    // -W clippy::all (NOT -A warnings: that group-allow would silence
    // clippy's lints too). Rustc's own warnings are filtered out below
    // so the report only carries clippy lints.
    cmd.args(["--edition", "2024", "--test", "--error-format=json", "-W", "clippy::all", "--emit=metadata"]);
    cmd.arg(&src).arg("-o").arg(&out);
    cmd.stdout(std::process::Stdio::piped()).stderr(std::process::Stdio::piped());

    let result = verifier::run_with_timeout(cmd, CLIPPY_TIMEOUT);
    let _ = std::fs::remove_dir_all(&dir);
    match result {
        Ok(verifier::RunOutcome::Done(output)) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let lints = verifier::parse_diagnostics(&stderr)
                .into_iter()
                .filter_map(|d| {
                    let lint = d.code?;
                    if !lint.starts_with("clippy::") {
                        return None;
                    }
                    let line = d.spans.first().map(|s| s.line_start).unwrap_or(0);
                    Some(ClippyLint { lint, message: d.message, line })
                })
                .collect();
            Some(lints)
        }
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// LLM review call (§4.2 layer 2)
// ---------------------------------------------------------------------------

/// One-shot JSON caller for the review/debrief LLM steps. The CLI
/// bridges this to `LlmClient` and records usage with the given phase
/// tag ("review" / "debrief" / "probe" — R6 分相计费).
pub trait ReviewCaller {
    fn call(&mut self, phase: &'static str, system: &str, user: &str, max_tokens: u32) -> Result<LlmReply>;
}

/// Inputs the reviewer sees. Everything comes from real artifacts
/// (template/draft + the user's file + index meta) — no fabrication.
pub struct ReviewInput<'a> {
    pub title: &'a str,
    pub concepts: &'a [String],
    /// The instruction part of the exercise (what the user saw).
    pub body: &'a str,
    /// Expected non-idiomatic patterns the exercise is designed to
    /// force away (template `anti_patterns`).
    pub anti_patterns: &'a [String],
    /// The language-transfer intuition behind the trap (template
    /// `confusion`), when available.
    pub confusion: Option<&'a str>,
    /// Hidden reference solution, when persisted (M5.1+).
    pub reference: Option<&'a str>,
    /// The user's full solution file (body + tests).
    pub user_code: &'a str,
    /// Attempts before the passing run (0 = first-try pass).
    pub attempts: u32,
}

const REVIEW_MAX_TOKENS: u32 = 1200;

const REVIEW_SYSTEM: &str = "\
你是 Rust 教练的解答评审器。学习者刚通过了一道 rustlings 式填空小题的全部测试，\
你要判断解答是否「通过但有问题」：更地道的标准写法、多余 clone、能用迭代器却手写循环、\
能用 &str 却用了 String、权限过宽、边界处理粗糙等。只基于给出的代码与参考解判断，不要臆测。\
严格只输出一个 JSON 对象（不要多余文字、不要代码围栏）：
{\"verdict\":\"clean|suggestions|suspicious\",\"summary\":\"一句话总评\",\"findings\":[{\"kind\":\"idiom|readability|maintenance|design|logic\",\"severity\":\"minor|major\",\"message\":\"问题描述（中文，具体到行为止）\",\"better_way\":\"具体改法（中文）\"}]}
verdict 判据：clean=惯用且无显著问题；suggestions=能过但有明确改进点；\
suspicious=疑似绕过考点（如死代码里的 todo!、硬编码测试期望值、空壳实现、测试被改弱）。\
findings 可为空数组；给不出具体改法就不要编造。";

fn review_user_prompt(input: &ReviewInput) -> String {
    let mut p = String::new();
    p.push_str(&format!("题目：《{}》\n", input.title));
    if !input.concepts.is_empty() {
        p.push_str(&format!("概念：{}\n", input.concepts.join("、")));
    }
    p.push_str(&format!("做题尝试次数：{}（0 = 一次通过）\n\n", input.attempts));
    p.push_str("【题面】\n");
    p.push_str(input.body.trim());
    p.push_str("\n\n【学习者的解答（已通过全部测试）】\n```rust\n");
    p.push_str(input.user_code.trim());
    p.push_str("\n```\n");
    if let Some(r) = input.reference {
        p.push_str("\n【参考解】\n```rust\n");
        p.push_str(r.trim());
        p.push_str("\n```\n");
    }
    if !input.anti_patterns.is_empty() {
        p.push_str("\n【本题预期迫使学习者避开的写法】\n");
        for a in input.anti_patterns {
            p.push_str(&format!("- {a}\n"));
        }
    }
    if let Some(c) = input.confusion {
        p.push_str(&format!("\n【本题针对的语言迁移直觉】{c}\n"));
    }
    p.push_str("\n请输出评审 JSON。");
    p
}

/// Ask the model for a solution review. Fails (Err) on transport /
/// truncation / unparseable JSON — the caller then falls back to the
/// static-only verdict and says so honestly.
pub fn llm_review(call: &mut dyn ReviewCaller, input: &ReviewInput) -> Result<LlmReview> {
    let reply = call.call("review", REVIEW_SYSTEM, &review_user_prompt(input), REVIEW_MAX_TOKENS)?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("评审输出在 max_tokens 处被截断");
    }
    parse_llm_review(&reply.content).ok_or_else(|| anyhow!("评审 JSON 无法解析"))
}

// ---------------------------------------------------------------------------
// Probe test (§4.2 suspicious path)
// ---------------------------------------------------------------------------

/// Result of the extra verification test for a suspicious solution.
#[derive(Debug, Clone)]
pub struct ProbeOutcome {
    /// The test module the LLM produced (already appended & compiled).
    pub test_code: String,
    /// None = the probe itself failed to compile/run (treated as
    /// inconclusive, NOT as a pass).
    pub passed: Option<bool>,
    /// Human-readable failure output when it did not pass.
    pub failure: Option<String>,
}

const PROBE_MAX_TOKENS: u32 = 800;

const PROBE_SYSTEM: &str = "\
你为 Rust 练习生成一道附加验证测试（probe test）。学习者的解答通过了原测试，但被评审判定为\
「疑似绕过考点」。你的任务：写一个**最小**的附加测试，直接检验本题的核心行为是否真正实现\
（而不是重新检验原测试已经覆盖的东西）。严格只输出一个 JSON 对象：
{\"reasoning\":\"一句话：这个测试为什么能暴露绕过\",\"test\":\"完整的 #[cfg(test)] mod probe_tests { ... } 代码（Rust 源码，含 use super::*;）\"}
约束：测试必须编译通过；不得修改/删除已有代码；不得使用 unsafe / std::process / std::fs；\
不要在测试里写 todo!。test 字段的代码将被原样追加到学习者文件末尾编译运行。";

fn probe_user_prompt(input: &ReviewInput, suspicious_reason: &str) -> String {
    format!(
        "题目：《{}》\n概念：{}\n\n【题面】\n{}\n\n【学习者的解答】\n```rust\n{}\n```\n\n\
         【评审判为存疑的理由】{}\n\n请输出 probe test JSON。",
        input.title,
        input.concepts.join("、"),
        input.body.trim(),
        input.user_code.trim(),
        suspicious_reason,
    )
}

pub fn parse_probe(text: &str) -> Option<(String, String)> {
    let json = crate::llm::extract_json(text)?;
    let v: Value = serde_json::from_str(json).ok()?;
    let test = v.get("test")?.as_str()?.trim().to_string();
    if test.is_empty() {
        return None;
    }
    let reasoning = v
        .get("reasoning")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    Some((reasoning, test))
}

/// Generate and run the probe test against the user's file. Returns
/// `Ok(None)`-shaped results via `ProbeOutcome.passed = None` when the
/// probe itself could not be produced or compiled (inconclusive).
pub fn run_probe(
    call: &mut dyn ReviewCaller,
    input: &ReviewInput,
    suspicious_reason: &str,
) -> Result<ProbeOutcome> {
    let reply = call.call(
        "probe",
        PROBE_SYSTEM,
        &probe_user_prompt(input, suspicious_reason),
        PROBE_MAX_TOKENS,
    )?;
    if reply.finish_reason.as_deref() == Some("length") {
        bail!("probe 输出被截断");
    }
    let (_reasoning, test_code) =
        parse_probe(&reply.content).ok_or_else(|| anyhow!("probe JSON 无法解析"))?;

    // Compile + run exactly like a practice attempt: user file + probe.
    let mut source = input.user_code.trim_end().to_string();
    source.push_str("\n\n");
    source.push_str(&test_code);

    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let workdir = std::env::temp_dir().join(format!("rustlings_probe_{nanos}"));
    std::fs::create_dir_all(&workdir)?;
    let run = verifier::run_test_flow(&source, &workdir, "probe");
    let _ = std::fs::remove_dir_all(&workdir);
    let run = run?;
    if !run.compiled {
        return Ok(ProbeOutcome {
            test_code,
            passed: None,
            failure: Some(probe_failure_text(&run.diagnostics)),
        });
    }
    match run.test {
        Some(t) if t.ok => Ok(ProbeOutcome { test_code, passed: Some(true), failure: None }),
        Some(t) => {
            let failure = t
                .failures
                .first()
                .map(|f| {
                    let mut s = f.output.clone();
                    if s.chars().count() > 600 {
                        s = s.chars().take(600).collect();
                    }
                    s
                })
                .unwrap_or_else(|| "probe 测试未通过".to_string());
            Ok(ProbeOutcome { test_code, passed: Some(false), failure: Some(failure) })
        }
        None => Ok(ProbeOutcome { test_code, passed: None, failure: None }),
    }
}

fn probe_failure_text(diags: &[verifier::Diagnostic]) -> String {
    let mut s = String::new();
    for d in diags.iter().filter(|d| d.is_error()).take(3) {
        if !s.is_empty() {
            s.push('\n');
        }
        s.push_str(d.rendered.as_deref().unwrap_or(&d.message));
        if s.chars().count() > 600 {
            s = s.chars().take(600).collect();
            break;
        }
    }
    if s.is_empty() {
        s = "probe 测试编译失败".to_string();
    }
    s
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verdict_parse_and_order() {
        assert_eq!(Verdict::parse("clean"), Some(Verdict::Clean));
        assert_eq!(Verdict::parse(" Suspicious "), Some(Verdict::Suspicious));
        assert_eq!(Verdict::parse("nope"), None);
        assert!(Verdict::Suspicious > Verdict::Suggestions);
        assert!(Verdict::Suggestions > Verdict::Clean);
    }

    #[test]
    fn parse_llm_review_full_and_minimal() {
        let full = r#"前面废话
{"verdict":"suggestions","summary":"能用迭代器","findings":[{"kind":"idiom","severity":"minor","message":"手写循环","better_way":"用 map"},{"kind":"idiom","severity":"minor","message":""}]}
后面废话"#;
        let r = parse_llm_review(full).unwrap();
        assert_eq!(r.verdict, Verdict::Suggestions);
        assert_eq!(r.summary, "能用迭代器");
        assert_eq!(r.findings.len(), 1, "empty message filtered");
        assert_eq!(r.findings[0].better_way.as_deref(), Some("用 map"));

        let minimal = r#"{"verdict":"clean","summary":"ok","findings":[]}"#;
        let r = parse_llm_review(minimal).unwrap();
        assert_eq!(r.verdict, Verdict::Clean);
        assert!(r.findings.is_empty());

        assert!(parse_llm_review("not json").is_none());
        assert!(parse_llm_review(r#"{"verdict":"wrong","summary":""}"#).is_none());
    }

    #[test]
    fn combine_takes_the_worst_layer() {
        let mut st = StaticReport::default();
        assert_eq!(combine(&st, None), Verdict::Clean);

        // todo residue → suspicious even when the LLM says clean.
        st.todo_residue = vec![3];
        assert_eq!(combine(&st, Some(&LlmReview {
            verdict: Verdict::Clean,
            summary: String::new(),
            findings: vec![],
        })), Verdict::Suspicious);

        // Constraint violations beat clean.
        st.todo_residue.clear();
        st.violations.push(constraints::Violation {
            constraint: "no-clone".into(),
            line: 2,
            snippet: ".clone()".into(),
            message: "违反约束".into(),
        });
        assert_eq!(combine(&st, None), Verdict::Suggestions);

        // LLM suspicious wins over static suggestions.
        assert_eq!(combine(&st, Some(&LlmReview {
            verdict: Verdict::Suspicious,
            summary: String::new(),
            findings: vec![],
        })), Verdict::Suspicious);
    }

    #[test]
    fn static_checks_finds_residue_violations_and_lines() {
        let code = "// todo! in comment does not count\nfn f() -> u32 {\n    let s = \"x\".to_owned();\n    todo!()\n}\n";
        let report = static_checks(code, &["no-clone".to_string()]);
        assert_eq!(report.todo_residue, vec![4]);
        assert_eq!(report.violations.len(), 1);
        assert_eq!(report.violations[0].constraint, "no-clone");
        assert_eq!(report.effective_lines, 4, "comment line excluded");
        assert!(report.has_todo_residue() && report.has_constraint_violations());
    }

    #[test]
    fn clippy_either_runs_or_honestly_reports_unavailable() {
        // Environment-dependent: only assert consistency between the
        // availability probe and the run result.
        let avail = clippy_available();
        let lints = run_clippy("fn f() { let v: Vec<u32> = Vec::new(); v; }");
        if avail {
            assert!(lints.is_some(), "clippy installed but run failed");
        } else {
            assert!(lints.is_none());
        }
    }

    /// A cloned-heavy snippet should yield at least one clippy lint
    /// when clippy exists (redundant clone / unused variable family).
    #[test]
    fn clippy_flags_redundant_clone_when_available() {
        if !clippy_available() {
            return;
        }
        let code = "fn f(s: &str) -> String {\n    let a = s.to_string();\n    let b = a.clone();\n    b\n}\n";
        let lints = run_clippy(code).unwrap();
        assert!(!lints.is_empty(), "expected clippy lints, got none");
        assert!(lints.iter().all(|l| l.lint.contains("clippy::")), "{lints:?}");
    }

    #[test]
    fn parse_probe_extracts_test_field() {
        let reply = r##"{"reasoning":"检查空输入","test":"#[cfg(test)]\nmod probe_tests { use super::*; #[test] fn t() { assert!(true); } }"}"##;
        let (reasoning, test) = parse_probe(reply).unwrap();
        assert!(reasoning.contains("空输入"));
        assert!(test.contains("mod probe_tests"));
        assert!(parse_probe("{\"reasoning\":\"x\"}").is_none());
    }

    #[test]
    fn review_user_prompt_contains_all_sections() {
        let input = ReviewInput {
            title: "题",
            concepts: &["ownership.move".to_string()],
            body: "// TODO",
            anti_patterns: &["clone 逃逸".to_string()],
            confusion: Some("来自 C 的值语义直觉"),
            reference: Some("fn f() {}"),
            user_code: "fn f() { todo!() }",
            attempts: 2,
        };
        let p = review_user_prompt(&input);
        assert!(p.contains("题面") && p.contains("参考解") && p.contains("clone 逃逸"));
        assert!(p.contains("语言迁移直觉") && p.contains("2"));
    }
}
